---
title: "linear_models"
author: "Siquan"
date: "11/7/2019"
output: github_document
---

```{r}
library(tidyverse)
library(p8105.datasets)
set.seed(1)
```
```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    boro = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  select(price, stars, boro, neighborhood, room_type)
```

```{r}
fit = lm(price ~ stars + boro, data = nyc_airbnb)
summary(fit)
coef(fit)
```

Tidy the result instead

```{r}
fit %>% 
  broom::tidy() %>% 
  mutate(term = str_replace(term, "boro", "Boro:")) %>% 
  knitr::kable(digits = 3)
```

##Take a look at factors...
```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(
    boro = fct_infreq(boro),
    room_type = fct_infreq(room_type))

fit = lm(price ~ stars + boro, data = nyc_airbnb)
fit %>% 
  broom::tidy()
fit %>% 
  broom::glance()
```

##Diagnostic
```{r}
modelr::add_residuals(nyc_airbnb, fit)
modelr::add_predictions(nyc_airbnb, fit)
nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x = boro, y = resid)) + geom_violin()
nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x = stars, y = resid)) + geom_point()
```

##Everyone loves nesting!
```{r}
nyc_airbnb %>% 
  lm(price ~ stars * boro + room_type * boro, data = .) %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 3)
```
```{r}
nest_lm_res =
nyc_airbnb %>% 
  nest(data = -boro) %>% 
  mutate(
    models = map(.x = data, ~lm(price~stars+room_type,data=.x)),
    results = map(models, broom::tidy)
  ) %>% 
  select(boro, results) %>% 
  unnest(results)
```

```{r}
nest_lm_res %>% 
  select(boro, term, estimate) %>% 
  mutate(term = fct_inorder(term)) %>% 
  pivot_wider(
    names_from = term, values_from = estimate) %>% 
  knitr::kable(digits = 3)
```

