---
title: "Tidy"
author: "Siquan"
date: "9/24/2019"
output: github_document
---
```{r}
#Reinstall it since new functions has been added one week ago #install.packages("tidyr")
library(tidyverse)
```

```{r}
pulse_data =
  haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()

pivot_longer(
  pulse_data,
  bdi_score_bl:bdi_score_12m,
  names_to = "visit",
  names_prefix = "bdi_score_",#Clean the name (the prefix is not useful and annoying)
  values_to = "bdi"
)%>% #What columns you need to scratch out : bdi_score_bl:bdi_score_12m change from long format to wide format
#Then it produces two new columns and you need to name them
mutate(
  visit = recode(visit, "bl"="00m")#For any element in column visit, if it has name bl, change it to oom
)
```

```{r}
read_csv("./data_import_examples/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  separate(col=group, into = c("does","day_of_tx"),3)#Seperate the original column of group into two new columns: does and day_of_tx, and separate at the third characteristics.
```
#Go untidy
```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)

analysis_result
pivot_wider(
  analysis_result, 
  names_from = "time", 
  values_from = "mean")
#Long format is easy to do presentation, wide format is easy to do analysis
```
#Binding Rows
```{r}
fellowship_data =
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "B3:D6") %>% 
  mutate(movie="fellowship")#Add one more column
  #We donnot need to read everything, we only need to read in certain cells

two_towers = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")
bind_rows(fellowship_data,two_towers,return_king) %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    female:male,
    names_to = "sex",
    values_to = "words"
  ) %>% 
  select(movie,race,sex,words)
#Then tidy it 

```
Joining datasets

```{r}
pup_data = 
  read_csv("./data_import_examples/FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, `1` = "male", `2` = "female")) 

litter_data = 
  read_csv("./data_import_examples/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group))
```
try to join the data sets!
```{r}
fas_data =
  left_join(pup_data, litter_data, by = "litter_number")#need to identify the key to join---Very important
#You could specify joining by multiple columns like: by = c("litter_number","XX" )
#Also could use full_join and other types of joing
```


